"""Configuration constants for QRL implementation."""

NUM_QUBITS = 4
REUPLOADING = True
REPS = 6
ACTION_SPACE = 2
INPUT_SHAPE = [4]

REPLAY_MEMORY_SIZE = 2000
BATCH_SIZE = 16
DISCOUNT_RATE = 0.99
LEARNING_RATE = 1e-2

MAX_EPISODES = 2000
MAX_STEPS_PER_EPISODE = 200
TARGET_SCORE = 200
TRAINING_START_EPISODE = 20
EXPLORATION_DECAY_EPISODES = 1500
MIN_EPSILON = 0.01

ENV_NAME = "CartPole-v1"

